<?php

namespace Gallery\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumImagesRepository extends EntityRepository
{

}
